
import 'package:iti_project/features/data/models/Random.dart';
import 'package:dio/dio.dart';
import 'package:iti_project/features/data/source/SourceApi.dart';

/*import 'package:dio/dio.dart';
import 'package:iti_project/features/data/models/Foods_model.dart';

import 'package:iti_project/features/data/source/SourceApi.dart';

class PostFood {

  Foodss api = Foodss();

  Future<List<Autogenerated>> fetchfoods() async {
    try {
      Response response = await api.sendRequest.get("/api/json/v1/1/search.php?s=chicken");
      List<dynamic> postMaps = response.data;
     
      return postMaps.map((postMap) => Autogenerated.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }
}*/



class DioService {
  final Dio _dio = Dio();

  DioService() {
    _dio.options.baseUrl = 'https://fakestoreapi.com/api/json/v1/1/search.php?s=chicken';
  }

  Future<Map<String, dynamic>> getRequest() async {
    try {
      final response = await _dio.get('https://fakestoreapi.com/api/json/v1/1/search.php?s=chicken');
      return response.data;
    } catch (e) {
      throw Exception('Failed to load data');
    }
  }
}







 /* Drinkss api2= Drinkss();
  Future<List<Drinnks>> fetchdrinks() async {
    try {
      Response response = await api.sendRequest.get("/api/json/v1/1/search.php?s=margarita");
      List<dynamic> postMaps = response.data;
      return postMaps.map((postMap) => Drinnks.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }
}
///////////////////////////////////////////////////
class PostDrink {

  Drinkss api= Drinkss();
  Future<List<Drinnks>> fetchdrinks() async {
    try {
      Response response = await api.sendRequest.get("/api/json/v1/1/search.php?s=margarita");
      List<dynamic> postMaps = response.data;
      return postMaps.map((postMap) => Drinnks.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }
}
///////////////////////////////////////////////////
class PostRandom {

  Ranndomm api = Ranndomm();
  Future<List<Randomm>> fetchRandom() async {
    try {
      Response response = await api.sendRequest.get("/products");
      List<dynamic> postMaps = response.data;
      return postMaps.map((postMap) => Randomm.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }
}
///////////////////////////////////////////////////
class PostFruit {

  Fruitss api = Fruitss();
  Future<List<Fruits>> fetchfruits() async {
    try {
      Response response = await api.sendRequest.get("/api/fruit/all");
      List<dynamic> postMaps = response.data;
      return postMaps.map((postMap) => Fruits.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }*/

class PostRandom {

  Ranndomm api = Ranndomm();
  Future<List<Randomm>> fetchRandom() async {
    try {
      Response response = await api.sendRequest.get("/products");
      List<dynamic> postMaps = response.data;
      return postMaps.map((postMap) => Randomm.fromJson(postMap)).toList();
    }
    catch(ex) {
      throw ex;
    }
  }
}